apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatapp
  namespace: dev
  labels:
    app: tomcatapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcatapp
  template:
    metadata: 
      labels:
        app: tomcatapp
    spec:
      containers:
      - name: tomcat-container
        image: engineervk/tomcat:1.0.0
        ports:
        - containerPort: 8082



  